export { default as Header } from "./header";
export { default as TextComponent } from "./textComponent";
export { default as Page } from "./page";
export { default as Paragraph } from "./paragraph";
export { default as Project } from "./project";
export { default as ProjectImage } from "./projectImage";
export { default as CoverImage } from "./coverImage";
export { default as Footer } from "./footer";
export { default as AnimationSection } from "./animationSection";
